title: know yourself
author: me
email: atslhnr99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  dont limit yourself, do whats you want and dont let anyone 
  bring you down.

# social links
twitter_username: 0732sta
github_username:  0732sta
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
